public class Circle extends Shape implements Drawable{
    private double radius;
    public Circle(String color, double radius){
        this.color = color; this.radius = radius;
    }
    @Override
    public double getArea(){
        return Math.PI*radius*radius;
    }
    @Override
    public double getPerimeter(){
        return 2*Math.PI*radius;
    }
    @Override
    public void draw(){
        System.out.println("Draw a rectangle");
    }
}